CONFIG_ZMK_KEYBOARD_NAME="Custom Split"
CONFIG_ZMK_SPLIT=y

# Enable USB
CONFIG_ZMK_USB=y

# Experimental Bluetooth fixes to resolve the "net" issue and pairing problems
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
